like_publication:
  path: /like/{id}
  defaults: { _controller: AppBundle:Like:like, id:null }
  methods: [POST]

unlike_publication:
  path: /unlike/{id}
  defaults: { _controller: AppBundle:Like:unlike, id:null }
  methods: [POST]

user_likes:
  path: /likes/{nickname}
  defaults: { _controller: AppBundle:Like:likes, nickname: null }